[auth_servers]
[auth_servers.default]
client_id = "0oa7c2btjqyKDevU2357"
issuer = "https://auth.qcs.rigetti.com/oauth2/aus8jcovzG0gW2TUG355"

[profiles]
[profiles.default]
api_url = "https://api.qcs.rigetti.com"
